/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Output {
  success: boolean;
  message: string;
  data: {
    $metadata: {
      httpStatusCode: number;
      requestId: string;
      extendedRequestId?: string;
      attempts: number;
      totalRetryDelay: number;
    };
    Layers: {
      LayerName: string;
      LayerArn: string;
      LatestMatchingVersion: {
        LayerVersionArn: string;
        Version: number;
        Description?: string;
        CreatedDate: string;
        CompatibleRuntimes: string[];
        LicenseInfo?: string;
      };
    }[];
  };
}
