/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  /**
   * The name of the layer.
   */
  layerName: string;
  /**
   * The runtime identifier to filter the list of layer versions.
   */
  compatibleRuntime?: string;
  /**
   * The maximum number of versions to return.
   */
  limit?: number;
}
