/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Input {
  /**
   * The URL to trigger the Lambda function.
   */
  url: string;
  /**
   * The JSON body to send as payload.
   */
  jsonBody?: string;
}
